version: '3'

name: "spring-activemq"
services:
  producer:
    build:
      context: "./producer"
      dockerfile: Dockerfile
    image: "producer:prod"
    container_name: "producer"
    ports:
      - "8081:8080"
    networks: 
      - mqNetwork
    volumes:
      - ./producer:/app
  
  consumer:
    build:
      context: "./consumer"
      dockerfile: Dockerfile
    image: "consumer:prod"
    container_name: "consumer"
    ports:
      - "8082:8080"
    networks: 
      - mqNetwork
    volumes:
      - ./consumer:/app

  activemq:
    image: rmohr/activemq
    container_name: "activemq"
    expose:
      - "61616"
    ports:
      - "8161:8161"
    networks: 
      - mqNetwork

networks:
  mqNetwork:
    driver: bridge